export const VILLA_LONG_DESCRIPTIONS: Record<string, string> = {
  mawar:
    "Nestled within the lush Sunshoot Villas Complex on Jl. Bidadari II E, Villa Mawar is a stunning two-storey garden villa just minutes from the heart of Seminyak. The famous Seminyak Beach is a short 10-minute walk away, while world-class restaurants, beach clubs, and boutique shops are all within easy reach. The villa features a generous open-plan living and dining area that flows seamlessly to your private pool, surrounded by tropical gardens. With two beautifully appointed bedrooms, Villa Mawar is ideal for families, couples travelling together, or small groups looking for a private Bali retreat. The warm and attentive Sunshoot team, including your dedicated housekeeper and friendly host Warren, are always on hand to make your stay exceptional.",
  jepun:
    "Located in the beating heart of Seminyak, Villa Jepun puts you within walking distance of Bali's most celebrated beach clubs, fine dining restaurants, and luxury boutiques. Seminyak Beach is just 10 minutes on foot. This beautifully designed two-bedroom villa blends modern elegance with traditional Balinese architecture, featuring queen-size beds with premium linens, modern ensuites, and a serene private pool surrounded by tropical greenery. Villa Jepun is perfect for couples, honeymooners, or small families who want an intimate and stylish base for their Bali holiday. The Sunshoot team prides itself on personal, attentive service and your host Warren goes above and beyond to ensure every detail of your stay is taken care of.",
  anggrek:
    "Villa Anggrek is one of Bali's best kept secrets, offering incredible value without compromising on comfort or style. Set within the Sunshoot Villas Complex on Jl. Bidadari II E, the villa is just a short stroll from Seminyak's famous restaurants, markets, and beach. With a spacious open-plan living and dining area, two comfortable bedrooms, and a sparkling private pool, Villa Anggrek is perfect for couples and families with young children. Tech-savvy guests will appreciate the lightning-fast 20Mbps fiber optic WiFi, ideal for remote work or streaming. The Sunshoot team provides warm, personalised service and Warren's local knowledge means you will always have the best restaurant recommendations and activity tips at your fingertips.",
  sandat:
    "Situated in Seminyak's coveted Bidadari area, Villa Sandat is a spacious and beautifully appointed retreat that has everything you need for the perfect Bali holiday. Step outside and you are within walking distance of supermarkets, local warungs, international restaurants, salons, and Seminyak's iconic beach. The villa features two large bedrooms with ensuites, a fully equipped kitchen, generous living and dining spaces, and a stunning private pool. Hungry but do not want to head out? Sunshoot Food and Drinks delivers directly to your villa door. Villa Sandat suits everyone from romantic couples to multi-generational families and groups of friends. Your host Warren and the Sunshoot team are renowned for going above and beyond, ensuring every guest leaves with memories to last a lifetime.",
};

export function getVillaLongDescription(slug: string): string {
  return VILLA_LONG_DESCRIPTIONS[slug] ?? "";
}
